# Generated by Django 6.0.4 on 2026-04-17 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacion', 'Confirmación'), ('recordatorio', 'Recordatorio'), ('cancelacion', 'Cancelación')], max_length=20)),
                ('canal', models.CharField(max_length=20)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('enviado', models.BooleanField(default=False)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.turno')),
            ],
        ),
    ]
