# Generated by Django 6.0.4 on 2026-04-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('profesional', 'Profesional'), ('recepcionista', 'Recepcionista'), ('admin', 'Administrador')], max_length=20)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
    ]
