# Generated by Django 4.2 on 2026-05-06 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnos_app', '0003_horariodisponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodisponible',
            name='duracion_turno',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='horariodisponible',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
        migrations.AlterField(
            model_name='horariodisponible',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
