# Generated by Django 6.0.6 on 2026-06-21 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('turnos_app', '0004_horariodisponible_duracion_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.perfil'),
        ),
        migrations.AddField(
            model_name='turno',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turnos_app.profesional'),
        ),
        migrations.AddField(
            model_name='turno',
            name='servicio',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
